window.esdocSearchIndex = [
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~altquerysuggester",
    "class/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester.html",
    "<span>AltQuerySuggester</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html",
    "<span>BooleanIndex</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/BooleanIndex.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/booleanindex.js~index",
    "variable/index.html#static-variable-Index",
    "<span>Index</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/BooleanIndex.js</span>",
    "variable"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/index.js~index",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html",
    "<span>Index</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/Index.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html",
    "<span>NumberIndex</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/NumberIndex.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~processor",
    "variable/index.html#static-variable-Processor",
    "<span>Processor</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js</span>",
    "variable"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/processors/processor.js~processor",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html",
    "<span>Processor</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/processors/Processor.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html",
    "<span>QueryParser</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/query/QueryParser.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/results.js~results",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html",
    "<span>Results</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/Results.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/processors/sorter.js~sorter",
    "class/node-information-retrieval-boilerplate/src/processors/Sorter.js~Sorter.html",
    "<span>Sorter</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/processors/Sorter.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html",
    "<span>StringIndex</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/StringIndex.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js~stringqueryparser",
    "variable/index.html#static-variable-StringQueryParser",
    "<span>StringQueryParser</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js</span>",
    "variable"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html",
    "<span>StringQueryParser</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/query/StringQueryParser.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/system.js~system",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html",
    "<span>System</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/System.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js~system",
    "variable/index.html#static-variable-System",
    "<span>System</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js</span>",
    "variable"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/textindex.js~textindex",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html",
    "<span>TextIndex</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index/TextIndex.js</span>",
    "class"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~augmented",
    "function/index.html#static-function-augmented",
    "<span>augmented</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~binary",
    "function/index.html#static-function-binary",
    "<span>binary</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~count",
    "function/index.html#static-function-count",
    "<span>count</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/evaluate.js~evaluate",
    "function/index.html#static-function-evaluate",
    "<span>evaluate</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/evaluate.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js~evaluate",
    "variable/index.html#static-variable-evaluate",
    "<span>evaluate</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js</span>",
    "variable"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/misc/extractobjectvalues.js~extractobjectvalues",
    "function/index.html#static-function-extractObjectValues",
    "<span>extractObjectValues</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/misc/extractObjectValues.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~inversedocumentfrequency",
    "function/index.html#static-function-inverseDocumentFrequency",
    "<span>inverseDocumentFrequency</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~inversedocumentfrequencymax",
    "function/index.html#static-function-inverseDocumentFrequencyMax",
    "<span>inverseDocumentFrequencyMax</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~inversedocumentfrequencysmooth",
    "function/index.html#static-function-inverseDocumentFrequencySmooth",
    "<span>inverseDocumentFrequencySmooth</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~lognormal",
    "function/index.html#static-function-logNormal",
    "<span>logNormal</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~naivebayes",
    "function/index.html#static-function-naiveBayes",
    "<span>naiveBayes</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~probabilisticinversedocumentfrequency",
    "function/index.html#static-function-probabilisticInverseDocumentFrequency",
    "<span>probabilisticInverseDocumentFrequency</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js~processors",
    "variable/index.html#static-variable-processors",
    "<span>processors</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js</span>",
    "variable"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js~scores",
    "variable/index.html#static-variable-scores",
    "<span>scores</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/index.js</span>",
    "variable"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~termfrequency",
    "function/index.html#static-function-termFrequency",
    "<span>termFrequency</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js~unary",
    "function/index.html#static-function-unary",
    "<span>unary</span> <span class=\"search-result-import-path\">information-retrieval-boilerplate/node-information-retrieval-boilerplate/src/scores/index.js</span>",
    "function"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~String",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~function",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~null",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~number",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~object",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~string",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "node-information-retrieval-boilerplate/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "node-information-retrieval-boilerplate/src/document.js",
    "file/node-information-retrieval-boilerplate/src/Document.js.html",
    "node-information-retrieval-boilerplate/src/Document.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/document.js~document",
    "typedef/index.html#static-typedef-Document",
    "node-information-retrieval-boilerplate/src/Document.js~Document",
    "typedef"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js",
    "file/node-information-retrieval-boilerplate/src/Results.js.html",
    "node-information-retrieval-boilerplate/src/Results.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#addhit",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-method-addHit",
    "node-information-retrieval-boilerplate/src/Results.js~Results#addHit",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#addkeyword",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-method-addKeyword",
    "node-information-retrieval-boilerplate/src/Results.js~Results#addKeyword",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#concat",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-method-concat",
    "node-information-retrieval-boilerplate/src/Results.js~Results#concat",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#constructor",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/Results.js~Results#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#invert",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-method-invert",
    "node-information-retrieval-boilerplate/src/Results.js~Results#invert",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#keywords",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-member-keywords",
    "node-information-retrieval-boilerplate/src/Results.js~Results#keywords",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#merge",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-method-merge",
    "node-information-retrieval-boilerplate/src/Results.js~Results#merge",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#normalise",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-method-normalise",
    "node-information-retrieval-boilerplate/src/Results.js~Results#normalise",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/results.js~results#results",
    "class/node-information-retrieval-boilerplate/src/Results.js~Results.html#instance-member-results",
    "node-information-retrieval-boilerplate/src/Results.js~Results#results",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js",
    "file/node-information-retrieval-boilerplate/src/System.js.html",
    "node-information-retrieval-boilerplate/src/System.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#adddocuments",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-addDocuments",
    "node-information-retrieval-boilerplate/src/System.js~System#addDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#addindex",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-addIndex",
    "node-information-retrieval-boilerplate/src/System.js~System#addIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#addprocessor",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-addProcessor",
    "node-information-retrieval-boilerplate/src/System.js~System#addProcessor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#constructor",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/System.js~System#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#getandresults",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-getAndResults",
    "node-information-retrieval-boilerplate/src/System.js~System#getAndResults",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#getfilterresults",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-getFilterResults",
    "node-information-retrieval-boilerplate/src/System.js~System#getFilterResults",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#getnotresults",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-getNotResults",
    "node-information-retrieval-boilerplate/src/System.js~System#getNotResults",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#getorresults",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-getOrResults",
    "node-information-retrieval-boilerplate/src/System.js~System#getOrResults",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#getresults",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-getResults",
    "node-information-retrieval-boilerplate/src/System.js~System#getResults",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#helpergetindex",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-helperGetIndex",
    "node-information-retrieval-boilerplate/src/System.js~System#helperGetIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#helperremoveindices",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-helperRemoveIndices",
    "node-information-retrieval-boilerplate/src/System.js~System#helperRemoveIndices",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#idfield",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-member-idField",
    "node-information-retrieval-boilerplate/src/System.js~System#idField",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#indices",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-member-indices",
    "node-information-retrieval-boilerplate/src/System.js~System#indices",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#meta",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-meta",
    "node-information-retrieval-boilerplate/src/System.js~System#meta",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#processors",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-member-processors",
    "node-information-retrieval-boilerplate/src/System.js~System#processors",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#processorslookup",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-member-processorsLookup",
    "node-information-retrieval-boilerplate/src/System.js~System#processorsLookup",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#removedocuments",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-removeDocuments",
    "node-information-retrieval-boilerplate/src/System.js~System#removeDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#retrievedocuments",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-retrieveDocuments",
    "node-information-retrieval-boilerplate/src/System.js~System#retrieveDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#state",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-state",
    "node-information-retrieval-boilerplate/src/System.js~System#state",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/system.js~system#updatedocuments",
    "class/node-information-retrieval-boilerplate/src/System.js~System.html#instance-method-updateDocuments",
    "node-information-retrieval-boilerplate/src/System.js~System#updateDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/evaluate.js",
    "file/node-information-retrieval-boilerplate/src/evaluate.js.html",
    "node-information-retrieval-boilerplate/src/evaluate.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/index.js",
    "file/node-information-retrieval-boilerplate/src/index.js.html",
    "node-information-retrieval-boilerplate/src/index.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js",
    "file/node-information-retrieval-boilerplate/src/index/BooleanIndex.js.html",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#addtoindex",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-method-addToIndex",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#addToIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#analysevalues",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-method-analyseValues",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#analyseValues",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#constructor",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#createindex",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-method-createIndex",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#createIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#filterbasedonindex",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-method-filterBasedOnIndex",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#filterBasedOnIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#filterexistsimpl",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-method-filterExistsImpl",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#filterExistsImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#filterisimpl",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-method-filterIsImpl",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#filterIsImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#filters",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-member-filters",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#filters",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#getdocumentvalues",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-method-getDocumentValues",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#getDocumentValues",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/booleanindex.js~booleanindex#removefromindex",
    "class/node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex.html#instance-method-removeFromIndex",
    "node-information-retrieval-boilerplate/src/index/BooleanIndex.js~BooleanIndex#removeFromIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js",
    "file/node-information-retrieval-boilerplate/src/index/Index.js.html",
    "node-information-retrieval-boilerplate/src/index/Index.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#adddocuments",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-addDocuments",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#addDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#addtoindex",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-addToIndex",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#addToIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#analysevalue",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-analyseValue",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#analyseValue",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#analysevalues",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-analyseValues",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#analyseValues",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#constructor",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#createindex",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-createIndex",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#createIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#entropy",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-member-entropy",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#entropy",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#fields",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-member-fields",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#fields",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#filterbasedonindex",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-filterBasedOnIndex",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#filterBasedOnIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#filterdocuments",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-filterDocuments",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#filterDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#filters",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-member-filters",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#filters",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#getdocumentvalues",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-getDocumentValues",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#getDocumentValues",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#index",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-member-index",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#index",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#removedocuments",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-removeDocuments",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#removeDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#removefromindex",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-removeFromIndex",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#removeFromIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#sorts",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-member-sorts",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#sorts",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#state",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-method-state",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#state",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#type",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-member-type",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#type",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/index.js~index#values",
    "class/node-information-retrieval-boilerplate/src/index/Index.js~Index.html#instance-member-values",
    "node-information-retrieval-boilerplate/src/index/Index.js~Index#values",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js",
    "file/node-information-retrieval-boilerplate/src/index/NumberIndex.js.html",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#addtoindex",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-addToIndex",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#addToIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#analysevalues",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-analyseValues",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#analyseValues",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#constructor",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#createindex",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-createIndex",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#createIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#filterbasedonindex",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-filterBasedOnIndex",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#filterBasedOnIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#filterequaltoimpl",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-filterEqualToImpl",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#filterEqualToImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#filterexistsimpl",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-filterExistsImpl",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#filterExistsImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#filterlessthanimpl",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-filterLessThanImpl",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#filterLessThanImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#filtermorethanimpl",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-filterMoreThanImpl",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#filterMoreThanImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#filters",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-member-filters",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#filters",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#getdocumentvalues",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-getDocumentValues",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#getDocumentValues",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/numberindex.js~numberindex#removefromindex",
    "class/node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex.html#instance-method-removeFromIndex",
    "node-information-retrieval-boilerplate/src/index/NumberIndex.js~NumberIndex#removeFromIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js",
    "file/node-information-retrieval-boilerplate/src/index/StringIndex.js.html",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#addtoindex",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-method-addToIndex",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#addToIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#constructor",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#createindex",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-method-createIndex",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#createIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#filterbasedonindex",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-method-filterBasedOnIndex",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#filterBasedOnIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#filterexistsimpl",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-method-filterExistsImpl",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#filterExistsImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#filtermatchimpl",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-method-filterMatchImpl",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#filterMatchImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#filters",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-member-filters",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#filters",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#getdocumentvalues",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-method-getDocumentValues",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#getDocumentValues",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/stringindex.js~stringindex#removefromindex",
    "class/node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex.html#instance-method-removeFromIndex",
    "node-information-retrieval-boilerplate/src/index/StringIndex.js~StringIndex#removeFromIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js",
    "file/node-information-retrieval-boilerplate/src/index/TextIndex.js.html",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#addtoindex",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-addToIndex",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#addToIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#allowpartialmatch",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-allowPartialMatch",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#allowPartialMatch",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#analysevalue",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-analyseValue",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#analyseValue",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#constructor",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#createindex",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-createIndex",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#createIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#decoder",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-decoder",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#decoder",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#filterbasedonindex",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-filterBasedOnIndex",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#filterBasedOnIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#filterqueryimpl",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-filterQueryImpl",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#filterQueryImpl",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#filters",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-filters",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#filters",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#getdocumentvalues",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-getDocumentValues",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#getDocumentValues",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#getsortvalue",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-getSortValue",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#getSortValue",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#lemm",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-lemm",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#lemm",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#lex",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-lex",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#lex",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#maximumdocumentsbyterm",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-maximumDocumentsByTerm",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#maximumDocumentsByTerm",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#removefromindex",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-removeFromIndex",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#removeFromIndex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#sorts",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-sorts",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#sorts",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#state",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-method-state",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#state",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#stem",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-stem",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#stem",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#tag",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-tag",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#tag",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/textindex.js~textindex#totalwordstally",
    "class/node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex.html#instance-member-totalWordsTally",
    "node-information-retrieval-boilerplate/src/index/TextIndex.js~TextIndex#totalWordsTally",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/index/register.js",
    "file/node-information-retrieval-boilerplate/src/index/register.js.html",
    "node-information-retrieval-boilerplate/src/index/register.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/misc/extractobjectvalues.js",
    "file/node-information-retrieval-boilerplate/src/misc/extractObjectValues.js.html",
    "node-information-retrieval-boilerplate/src/misc/extractObjectValues.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/altquerysuggester.js",
    "file/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js.html",
    "node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~altquerysuggester#adddocuments",
    "class/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester.html#instance-method-addDocuments",
    "node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester#addDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~altquerysuggester#constructor",
    "class/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~altquerysuggester#fields",
    "class/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester.html#instance-member-fields",
    "node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester#fields",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~altquerysuggester#getclosest",
    "class/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester.html#instance-method-getClosest",
    "node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester#getClosest",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~altquerysuggester#processresults",
    "class/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester.html#instance-method-processResults",
    "node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester#processResults",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~altquerysuggester#state",
    "class/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester.html#instance-method-state",
    "node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester#state",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/altquerysuggester.js~altquerysuggester#words",
    "class/node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester.html#instance-member-words",
    "node-information-retrieval-boilerplate/src/processors/AltQuerySuggester.js~AltQuerySuggester#words",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js",
    "file/node-information-retrieval-boilerplate/src/processors/Processor.js.html",
    "node-information-retrieval-boilerplate/src/processors/Processor.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js~processor#adddocuments",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html#instance-method-addDocuments",
    "node-information-retrieval-boilerplate/src/processors/Processor.js~Processor#addDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js~processor#bind",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html#instance-member-bind",
    "node-information-retrieval-boilerplate/src/processors/Processor.js~Processor#bind",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js~processor#constructor",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/processors/Processor.js~Processor#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js~processor#processquery",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html#instance-method-processQuery",
    "node-information-retrieval-boilerplate/src/processors/Processor.js~Processor#processQuery",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js~processor#processresults",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html#instance-method-processResults",
    "node-information-retrieval-boilerplate/src/processors/Processor.js~Processor#processResults",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js~processor#removedocuments",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html#instance-method-removeDocuments",
    "node-information-retrieval-boilerplate/src/processors/Processor.js~Processor#removeDocuments",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js~processor#state",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html#instance-method-state",
    "node-information-retrieval-boilerplate/src/processors/Processor.js~Processor#state",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/processor.js~processor#type",
    "class/node-information-retrieval-boilerplate/src/processors/Processor.js~Processor.html#instance-member-type",
    "node-information-retrieval-boilerplate/src/processors/Processor.js~Processor#type",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/sorter.js",
    "file/node-information-retrieval-boilerplate/src/processors/Sorter.js.html",
    "node-information-retrieval-boilerplate/src/processors/Sorter.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/sorter.js~sorter#constructor",
    "class/node-information-retrieval-boilerplate/src/processors/Sorter.js~Sorter.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/processors/Sorter.js~Sorter#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/sorter.js~sorter#processresults",
    "class/node-information-retrieval-boilerplate/src/processors/Sorter.js~Sorter.html#instance-method-processResults",
    "node-information-retrieval-boilerplate/src/processors/Sorter.js~Sorter#processResults",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/sorter.js~sorter#sortfunction",
    "class/node-information-retrieval-boilerplate/src/processors/Sorter.js~Sorter.html#instance-method-sortFunction",
    "node-information-retrieval-boilerplate/src/processors/Sorter.js~Sorter#sortFunction",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/processors/register.js",
    "file/node-information-retrieval-boilerplate/src/processors/register.js.html",
    "node-information-retrieval-boilerplate/src/processors/register.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/query.js",
    "file/node-information-retrieval-boilerplate/src/query/Query.js.html",
    "node-information-retrieval-boilerplate/src/query/Query.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/query.js~query",
    "typedef/index.html#static-typedef-Query",
    "node-information-retrieval-boilerplate/src/query/Query.js~Query",
    "typedef"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/query.js~queryfilter",
    "typedef/index.html#static-typedef-QueryFilter",
    "node-information-retrieval-boilerplate/src/query/Query.js~QueryFilter",
    "typedef"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js",
    "file/node-information-retrieval-boilerplate/src/query/QueryParser.js.html",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#constructor",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#defaultexactfilter",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-member-defaultExactFilter",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#defaultExactFilter",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#defaultfield",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-member-defaultField",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#defaultField",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#defaultfilter",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-member-defaultFilter",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#defaultFilter",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#defaultsort",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-member-defaultSort",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#defaultSort",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#defaultsortorder",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-member-defaultSortOrder",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#defaultSortOrder",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#fields",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-member-fields",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#fields",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#getdefault",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-method-getDefault",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#getDefault",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/queryparser.js~queryparser#sort",
    "class/node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser.html#instance-member-sort",
    "node-information-retrieval-boilerplate/src/query/QueryParser.js~QueryParser#sort",
    "member"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js",
    "file/node-information-retrieval-boilerplate/src/query/StringQueryParser.js.html",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js",
    "file"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#classifychar",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-classifyChar",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#classifyChar",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#constructor",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-constructor-constructor",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#constructor",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#lemmatise",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-lemmatise",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#lemmatise",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#lex",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-lex",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#lex",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#parse",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-parse",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#parse",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#parsejoinallandortokens",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-parseJoinAllAndOrTokens",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#parseJoinAllAndOrTokens",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#parsejoinallexactmatchtokens",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-parseJoinAllExactMatchTokens",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#parseJoinAllExactMatchTokens",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#parsejoinallfieldtokens",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-parseJoinAllFieldTokens",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#parseJoinAllFieldTokens",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#parsejoinallnottokens",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-parseJoinAllNotTokens",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#parseJoinAllNotTokens",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#parsejoinallregulartokens",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-parseJoinAllRegularTokens",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#parseJoinAllRegularTokens",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#tokenise",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-tokenise",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#tokenise",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/query/stringqueryparser.js~stringqueryparser#treetofilters",
    "class/node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser.html#instance-method-treeToFilters",
    "node-information-retrieval-boilerplate/src/query/StringQueryParser.js~StringQueryParser#treeToFilters",
    "method"
  ],
  [
    "node-information-retrieval-boilerplate/src/scores/index.js",
    "file/node-information-retrieval-boilerplate/src/scores/index.js.html",
    "node-information-retrieval-boilerplate/src/scores/index.js",
    "file"
  ]
]